### ISSUE TITLE
Implement the `edition` meta data info

### ISSUE THREAD

**Issue by kopeckyf** [langsci/latex#155]
- [ ] Command `\edition` to store a literal
- [ ] Output edition info on cover
- [ ] Include ed. info in frontmatter and `@langsci-current-book` bib entry
- [ ] Include ed. info in the title footer of chapters
